"""Injects KNOWLEDGE_BASE.md references into AI agent instruction files.

Detects common AI agent configuration files (AGENTS.md, CLAUDE.md,
.cursorrules, etc.) and appends a pointer to KNOWLEDGE_BASE.md so
that agents can discover project context quickly without manual setup.

The injected text includes instructions for the agent to regenerate
KNOWLEDGE_BASE.md by running readmenator when needed.
"""

from __future__ import annotations

import glob
import logging
import subprocess
import sys
from pathlib import Path
from typing import List, Optional, Sequence

logger = logging.getLogger(__name__)

_ANCHOR = "<!-- readmenator-agent-kb-link -->"
_ANCHOR_END = "<!-- /readmenator-agent-kb-link -->"

_AGENT_FILES: tuple[str, ...] = (
    "AGENTS.md",
    "CLAUDE.md",
    "SOUL.md",
    "LLM.md",
    "CONVENTIONS.md",
    ".cursorrules",
    ".instructions.md",
    ".windsurfrules",
    ".aider.conf.yml",
    "SKILL.md",
    "GEMINI.md",
    "AGENTS.override.md",
    "RULES.md",
    "PROJECT_RULES.md",
    ".github/copilot-instructions.md",
)

_AGENT_GLOBS: tuple[str, ...] = (
    ".cursor/rules/*.mdc",
)

_INJECTION_MD = (
    "\n\n{anchor_start}\n"
    "## Project Knowledge Base\n"
    "\n"
    "This project contains analysis outputs generated by "
    "[ReadMenator](https://github.com/grisuno/ReadMenator), a zero-token "
    "polyglot static analysis tool.\n"
    "\n"
    "**For humans:** Read `{kb_filename}` -- full architecture reference.\n"
    "\n"
    "**For agents:** Read `{agent_output_dir}/INDEX.md` -- grep-friendly index.\n"
    "  - `{agent_output_dir}/INDEX.md` -- file -> purpose map (start here)\n"
    "  - `{agent_output_dir}/API.md` -- public functions + contracts\n"
    "  - `{agent_output_dir}/GOTCHAS.md` -- \"don't change X because Y breaks\"\n"
    "  - `{agent_output_dir}/KB_<subsystem>.md` -- per-subsystem context (grep-friendly)\n"
    "  - `{agent_output_dir}/SECURITY.md` -- findings by severity\n"
    "  - `{agent_output_dir}/recipes/*.md` -- actionable task blocks\n"
    "\n"
    "If outputs are outdated, regenerate by running:\n"
    "\n"
    "    pip install readmenator && readmenator .\n"
    "{anchor_end}\n"
)

_INJECTION_PLAIN = (
    "\n\n{anchor_start}\n"
    "Project Knowledge Base\n"
    "\n"
    "This project contains analysis outputs generated by "
    "ReadMenator (https://github.com/grisuno/ReadMenator), a zero-token "
    "polyglot static analysis tool.\n"
    "\n"
    "For humans: Read {kb_filename} -- full architecture reference.\n"
    "\n"
    "For agents: Read {agent_output_dir}/INDEX.md -- grep-friendly index.\n"
    "  - {agent_output_dir}/INDEX.md -- file -> purpose map (start here)\n"
    "  - {agent_output_dir}/API.md -- public functions + contracts\n"
    "  - {agent_output_dir}/GOTCHAS.md -- don't change X because Y breaks\n"
    "  - {agent_output_dir}/KB_<subsystem>.md -- per-subsystem context\n"
    "  - {agent_output_dir}/SECURITY.md -- findings by severity\n"
    "  - {agent_output_dir}/recipes/*.md -- actionable task blocks\n"
    "\n"
    "If outputs are outdated, regenerate by running:\n"
    "\n"
    "    pip install readmenator && readmenator .\n"
    "{anchor_end}\n"
)


def ensure_readmenator_installed() -> bool:
    """Check if readmenator is installed via pip; install it if missing.

    Returns True if readmenator is available after the check.
    """
    try:
        import readmenator  # noqa: F401
        return True
    except ImportError:
        pass
    logger.info("readmenator not found, installing via pip...")
    try:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "readmenator"],
        )
        logger.info("readmenator installed successfully")
        return True
    except subprocess.CalledProcessError:
        logger.warning(
            "Failed to install readmenator automatically. "
            "Install manually: pip install readmenator"
        )
        return False


class AgentInjector:
    """Injects a link to KNOWLEDGE_BASE.md into AI agent instruction files.

    Detects common AI agent configuration files (AGENTS.md, CLAUDE.md,
    .cursorrules, etc.) and appends a descriptive section pointing to
    the knowledge base so agents discover it automatically.

    The injected text instructs the agent how to regenerate the KB
    by running readmenator when needed.
    """

    def __init__(
        self,
        kb_filename: str = "KNOWLEDGE_BASE.md",
        agent_output_dir: str = "readmenator-agent",
        agent_files: Optional[Sequence[str]] = None,
        agent_globs: Optional[Sequence[str]] = None,
    ) -> None:
        self._kb_filename = kb_filename
        self._agent_output_dir = agent_output_dir
        self._agent_files = tuple(agent_files or _AGENT_FILES)
        self._agent_globs = tuple(agent_globs or _AGENT_GLOBS)

    def inject(self, project_root: str) -> int:
        """Inject KB reference into all discovered agent files.

        Returns the number of agent files actually modified.
        """
        root = Path(project_root).resolve()
        targets = self._find_agent_files(root)
        modified = 0
        for path in targets:
            if self._inject_single(path):
                modified += 1
        if modified:
            logger.info(
                "Injected knowledge base reference into %d agent file(s)",
                modified,
            )
        return modified

    def remove(self, project_root: str) -> int:
        """Remove KB injection from all discovered agent files.

        Returns the number of files actually modified.
        """
        root = Path(project_root).resolve()
        targets = self._find_agent_files(root)
        removed = 0
        for path in targets:
            if self._remove_single(path):
                removed += 1
        return removed

    def find_agent_files(self, project_root: str) -> List[Path]:
        """Public accessor: return all detected agent files."""
        return self._find_agent_files(Path(project_root).resolve())

    def _find_agent_files(self, root: Path) -> List[Path]:
        found: List[Path] = []
        for name in self._agent_files:
            path = root / name
            if path.is_file():
                found.append(path)
        for pattern in self._agent_globs:
            matches = glob.glob(str(root / pattern), recursive=False)
            for match in sorted(matches):
                p = Path(match)
                if p.is_file() and p not in found:
                    found.append(p)
        return found

    def _inject_single(self, path: Path) -> bool:
        content = path.read_text(encoding="utf-8", errors="replace")
        suffix = path.suffix.lower()
        if suffix in (".yml", ".yaml"):
            injection = self._build_injection("plain")
        else:
            injection = self._build_injection("markdown")

        if _ANCHOR in content:
            current = self._extract_current_injection(content)
            if current.strip() == injection.strip():
                logger.debug("Injection already up to date in %s", path.name)
                return False
            content = self._remove_old_injection(content)
            new_content = content.rstrip("\n") + injection
            path.write_text(new_content, encoding="utf-8")
            logger.info("Updated agent KB link in %s", path.name)
            return True

        new_content = content.rstrip("\n") + injection
        path.write_text(new_content, encoding="utf-8")
        logger.info("Injected agent KB link into %s", path.name)
        return True

    @staticmethod
    def _extract_current_injection(content: str) -> str:
        start_idx = content.find(_ANCHOR)
        end_idx = content.find(_ANCHOR_END)
        if start_idx < 0 or end_idx < 0:
            return ""
        end_idx += len(_ANCHOR_END)
        return content[start_idx:end_idx]

    @staticmethod
    def _remove_old_injection(content: str) -> str:
        start_idx = content.find(_ANCHOR)
        end_idx = content.find(_ANCHOR_END)
        if start_idx < 0 or end_idx < 0:
            return content
        end_idx += len(_ANCHOR_END)
        before = content[:start_idx].rstrip("\n")
        after = content[end_idx:].lstrip("\n")
        return before + ("\n" + after if after else "")

    def _remove_single(self, path: Path) -> bool:
        content = path.read_text(encoding="utf-8", errors="replace")
        if _ANCHOR not in content:
            return False
        start_idx = content.find(_ANCHOR)
        end_idx = content.find(_ANCHOR_END)
        if end_idx < 0:
            return False
        end_idx += len(_ANCHOR_END)
        before = content[:start_idx].rstrip("\n")
        after = content[end_idx:].lstrip("\n")
        new_content = before + ("\n" + after if after else "")
        path.write_text(new_content, encoding="utf-8")
        logger.debug("Removed KB injection from %s", path.name)
        return True

    def _build_injection(self, fmt: str) -> str:
        kwargs = dict(
            anchor_start=_ANCHOR,
            anchor_end=_ANCHOR_END,
            kb_filename=self._kb_filename,
            agent_output_dir=self._agent_output_dir,
        )
        if fmt == "plain":
            return _INJECTION_PLAIN.format(**kwargs)
        return _INJECTION_MD.format(**kwargs)
