// ReadMenator Knowledge Graph — Cypher export
// Nodes: 76, Edges: 5897

CREATE (f0:File {id: 'readmenator/__init__.py', label: '__init__.py', language: 'py', kind: 'module', community: 0})
CREATE (f1:File {id: 'readmenator/__main__.py', label: '__main__.py', language: 'py', kind: 'module', community: 0, symbol_count: 3})
CREATE (f2:File {id: 'readmenator/_analyzer.py', label: '_analyzer.py', language: 'py', kind: 'module', community: 0, symbol_count: 13})
CREATE (f3:File {id: 'readmenator/_app.py', label: '_app.py', language: 'py', kind: 'module', community: 0, symbol_count: 31})
CREATE (f4:File {id: 'readmenator/_cache.py', label: '_cache.py', language: 'py', kind: 'module', community: 0, symbol_count: 13})
CREATE (f5:File {id: 'readmenator/_category.py', label: '_category.py', language: 'py', kind: 'module', community: 0, symbol_count: 25})
CREATE (f6:File {id: 'readmenator/_config.py', label: '_config.py', language: 'py', kind: 'module', community: 0, symbol_count: 1})
CREATE (f7:File {id: 'readmenator/_cpg.py', label: '_cpg.py', language: 'py', kind: 'module', community: 0, symbol_count: 6})
CREATE (f8:File {id: 'readmenator/_documentation.py', label: '_documentation.py', language: 'py', kind: 'module', community: 0, symbol_count: 26})
CREATE (f9:File {id: 'readmenator/_explain.py', label: '_explain.py', language: 'py', kind: 'module', community: 0, symbol_count: 3})
CREATE (f10:File {id: 'readmenator/_exporter.py', label: '_exporter.py', language: 'py', kind: 'module', community: 0, symbol_count: 15})
CREATE (f11:File {id: 'readmenator/_hotspots.py', label: '_hotspots.py', language: 'py', kind: 'module', community: 0, symbol_count: 7})
CREATE (f12:File {id: 'readmenator/_layer_rules.py', label: '_layer_rules.py', language: 'py', kind: 'module', community: 0, symbol_count: 4})
CREATE (f13:File {id: 'readmenator/_layers.py', label: '_layers.py', language: 'py', kind: 'module', community: 0, symbol_count: 4})
CREATE (f14:File {id: 'readmenator/_mcp_server.py', label: '_mcp_server.py', language: 'py', kind: 'module', community: 0, symbol_count: 52})
CREATE (f15:File {id: 'readmenator/_mermaid.py', label: '_mermaid.py', language: 'py', kind: 'module', community: 0, symbol_count: 4})
CREATE (f16:File {id: 'readmenator/_models.py', label: '_models.py', language: 'py', kind: 'module', community: 0, symbol_count: 15})
CREATE (f17:File {id: 'readmenator/_pipeline.py', label: '_pipeline.py', language: 'py', kind: 'module', community: 0, symbol_count: 21})
CREATE (f18:File {id: 'readmenator/_projections.py', label: '_projections.py', language: 'py', kind: 'module', community: 0, symbol_count: 15})
CREATE (f19:File {id: 'readmenator/_query.py', label: '_query.py', language: 'py', kind: 'module', community: 0, symbol_count: 17})
CREATE (f20:File {id: 'readmenator/_rank.py', label: '_rank.py', language: 'py', kind: 'module', community: 0, symbol_count: 17})
CREATE (f21:File {id: 'readmenator/_resolver.py', label: '_resolver.py', language: 'py', kind: 'module', community: 0, symbol_count: 11})
CREATE (f22:File {id: 'readmenator/_rule_gen.py', label: '_rule_gen.py', language: 'py', kind: 'module', community: 0, symbol_count: 9})
CREATE (f23:File {id: 'readmenator/_sarif.py', label: '_sarif.py', language: 'py', kind: 'module', community: 0, symbol_count: 5})
CREATE (f24:File {id: 'readmenator/_scanner.py', label: '_scanner.py', language: 'py', kind: 'module', community: 0, symbol_count: 13})
CREATE (f25:File {id: 'readmenator/_security.py', label: '_security.py', language: 'py', kind: 'module', community: 0, symbol_count: 31})
CREATE (f26:File {id: 'readmenator/_taint.py', label: '_taint.py', language: 'py', kind: 'module', community: 0, symbol_count: 6})
CREATE (f27:File {id: 'readmenator/_watcher.py', label: '_watcher.py', language: 'py', kind: 'module', community: 0, symbol_count: 5})
CREATE (f28:File {id: 'readmenator/parsers/__init__.py', label: '__init__.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f29:File {id: 'readmenator/parsers/_assembly.py', label: '_assembly.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f30:File {id: 'readmenator/parsers/_base.py', label: '_base.py', language: 'py', kind: 'module', community: 1, symbol_count: 6})
CREATE (f31:File {id: 'readmenator/parsers/_c.py', label: '_c.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f32:File {id: 'readmenator/parsers/_csharp.py', label: '_csharp.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f33:File {id: 'readmenator/parsers/_dart.py', label: '_dart.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f34:File {id: 'readmenator/parsers/_elixir.py', label: '_elixir.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f35:File {id: 'readmenator/parsers/_gdscript.py', label: '_gdscript.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f36:File {id: 'readmenator/parsers/_go.py', label: '_go.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f37:File {id: 'readmenator/parsers/_java.py', label: '_java.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f38:File {id: 'readmenator/parsers/_javascript.py', label: '_javascript.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f39:File {id: 'readmenator/parsers/_kotlin.py', label: '_kotlin.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f40:File {id: 'readmenator/parsers/_lua.py', label: '_lua.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f41:File {id: 'readmenator/parsers/_nim.py', label: '_nim.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f42:File {id: 'readmenator/parsers/_php.py', label: '_php.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f43:File {id: 'readmenator/parsers/_python.py', label: '_python.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f44:File {id: 'readmenator/parsers/_ruby.py', label: '_ruby.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f45:File {id: 'readmenator/parsers/_rust.py', label: '_rust.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f46:File {id: 'readmenator/parsers/_scala.py', label: '_scala.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f47:File {id: 'readmenator/parsers/_shell.py', label: '_shell.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f48:File {id: 'readmenator/parsers/_swift.py', label: '_swift.py', language: 'py', kind: 'module', community: 1, symbol_count: 2})
CREATE (f49:File {id: 'readmenator.py', label: 'readmenator.py', language: 'py', kind: 'module', community: 0})
CREATE (f50:File {id: 'readmenator_orchestrator.py', label: 'readmenator_orchestrator.py', language: 'py', kind: 'module', symbol_count: 34})
CREATE (f51:File {id: 'tests/__init__.py', label: '__init__.py', language: 'py', kind: 'module'})
CREATE (f52:File {id: 'tests/test_analyzer.py', label: 'test_analyzer.py', language: 'py', kind: 'module', community: 0, symbol_count: 12})
CREATE (f53:File {id: 'tests/test_cache.py', label: 'test_cache.py', language: 'py', kind: 'module', community: 0, symbol_count: 22})
CREATE (f54:File {id: 'tests/test_config.py', label: 'test_config.py', language: 'py', kind: 'module', community: 0, symbol_count: 6})
CREATE (f55:File {id: 'tests/test_cpg.py', label: 'test_cpg.py', language: 'py', kind: 'module', community: 0, symbol_count: 11})
CREATE (f56:File {id: 'tests/test_documentation.py', label: 'test_documentation.py', language: 'py', kind: 'module', community: 0, symbol_count: 29})
CREATE (f57:File {id: 'tests/test_exporter.py', label: 'test_exporter.py', language: 'py', kind: 'module', community: 0, symbol_count: 15})
CREATE (f58:File {id: 'tests/test_hotspots.py', label: 'test_hotspots.py', language: 'py', kind: 'module', community: 0, symbol_count: 11})
CREATE (f59:File {id: 'tests/test_integration.py', label: 'test_integration.py', language: 'py', kind: 'module', community: 0, symbol_count: 16})
CREATE (f60:File {id: 'tests/test_layer_rules.py', label: 'test_layer_rules.py', language: 'py', kind: 'module', community: 0, symbol_count: 13})
CREATE (f61:File {id: 'tests/test_mcp_server.py', label: 'test_mcp_server.py', language: 'py', kind: 'module', community: 0, symbol_count: 25})
CREATE (f62:File {id: 'tests/test_mermaid.py', label: 'test_mermaid.py', language: 'py', kind: 'module', community: 0, symbol_count: 11})
CREATE (f63:File {id: 'tests/test_models.py', label: 'test_models.py', language: 'py', kind: 'module', community: 0, symbol_count: 11})
CREATE (f64:File {id: 'tests/test_parsers.py', label: 'test_parsers.py', language: 'py', kind: 'module', community: 0, symbol_count: 84})
CREATE (f65:File {id: 'tests/test_parsers_new.py', label: 'test_parsers_new.py', language: 'py', kind: 'module', community: 0, symbol_count: 36})
CREATE (f66:File {id: 'tests/test_parsers_property.py', label: 'test_parsers_property.py', language: 'py', kind: 'module', community: 1, symbol_count: 16})
CREATE (f67:File {id: 'tests/test_query.py', label: 'test_query.py', language: 'py', kind: 'module', community: 0, symbol_count: 18})
CREATE (f68:File {id: 'tests/test_ranking.py', label: 'test_ranking.py', language: 'py', kind: 'module', community: 0, symbol_count: 72})
CREATE (f69:File {id: 'tests/test_resolver.py', label: 'test_resolver.py', language: 'py', kind: 'module', community: 0, symbol_count: 11})
CREATE (f70:File {id: 'tests/test_rule_gen.py', label: 'test_rule_gen.py', language: 'py', kind: 'module', community: 0, symbol_count: 10})
CREATE (f71:File {id: 'tests/test_sarif.py', label: 'test_sarif.py', language: 'py', kind: 'module', community: 0, symbol_count: 10})
CREATE (f72:File {id: 'tests/test_scanner.py', label: 'test_scanner.py', language: 'py', kind: 'module', community: 0, symbol_count: 17})
CREATE (f73:File {id: 'tests/test_security.py', label: 'test_security.py', language: 'py', kind: 'module', community: 0, symbol_count: 63})
CREATE (f74:File {id: 'tests/test_taint.py', label: 'test_taint.py', language: 'py', kind: 'module', community: 0, symbol_count: 10})
CREATE (f75:File {id: 'tests/test_taint_bdd.py', label: 'test_taint_bdd.py', language: 'py', kind: 'module', community: 0, symbol_count: 26})

CREATE (f0)-[:IMPORTS {relation: 'resolved_imports'}]->(f3)
CREATE (f0)-[:IMPORTS {relation: 'resolved_imports'}]->(f5)
CREATE (f0)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f0)-[:IMPORTS {relation: 'resolved_imports'}]->(f14)
CREATE (f0)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f0)-[:IMPORTS {relation: 'resolved_imports'}]->(f20)
CREATE (f1)-[:IMPORTS {relation: 'resolved_imports'}]->(f3)
CREATE (f1)-[:IMPORTS {relation: 'resolved_imports'}]->(f14)
CREATE (f1)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f1)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f1)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f2)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f2)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f4)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f13)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f17)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f19)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f20)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f21)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f27)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f3)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f4)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f5)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f7)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f8)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f8)-[:IMPORTS {relation: 'resolved_imports'}]->(f7)
CREATE (f8)-[:IMPORTS {relation: 'resolved_imports'}]->(f15)
CREATE (f8)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f8)-[:IMPORTS {relation: 'resolved_imports'}]->(f20)
CREATE (f9)-[:IMPORTS {relation: 'resolved_imports'}]->(f5)
CREATE (f9)-[:IMPORTS {relation: 'resolved_imports'}]->(f20)
CREATE (f10)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f10)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f11)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f11)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f12)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f12)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f13)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f14)-[:IMPORTS {relation: 'resolved_imports'}]->(f3)
CREATE (f14)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f14)-[:IMPORTS {relation: 'resolved_imports'}]->(f13)
CREATE (f14)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f14)-[:IMPORTS {relation: 'resolved_imports'}]->(f19)
CREATE (f15)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f16)-[:IMPORTS {relation: 'resolved_imports'}]->(f5)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f2)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f5)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f7)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f8)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f10)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f11)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f12)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f13)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f20)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f22)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f23)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f24)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f25)
CREATE (f17)-[:IMPORTS {relation: 'resolved_imports'}]->(f26)
CREATE (f18)-[:IMPORTS {relation: 'resolved_imports'}]->(f5)
CREATE (f18)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f19)-[:IMPORTS {relation: 'resolved_imports'}]->(f5)
CREATE (f19)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f19)-[:IMPORTS {relation: 'resolved_imports'}]->(f20)
CREATE (f20)-[:IMPORTS {relation: 'resolved_imports'}]->(f5)
CREATE (f22)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f22)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f23)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f24)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f24)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f24)-[:IMPORTS {relation: 'resolved_imports'}]->(f28)
CREATE (f25)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f25)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f26)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f26)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f27)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f31)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f43)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f36)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f45)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f38)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f37)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f32)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f47)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f42)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f33)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f35)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f41)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f29)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f44)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f48)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f39)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f46)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f40)
CREATE (f28)-[:IMPORTS {relation: 'resolved_imports'}]->(f34)
CREATE (f29)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f29)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f30)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f30)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f31)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f31)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f32)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f32)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f33)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f33)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f34)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f34)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f35)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f35)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f36)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f36)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f37)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f37)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f38)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f38)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f39)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f39)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f40)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f40)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f41)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f41)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f42)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f42)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f43)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f43)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f44)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f44)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f45)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f45)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f46)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f46)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f47)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f47)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f48)-[:IMPORTS {relation: 'resolved_imports'}]->(f30)
CREATE (f48)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f49)-[:IMPORTS {relation: 'resolved_imports'}]->(f1)
CREATE (f52)-[:IMPORTS {relation: 'resolved_imports'}]->(f2)
CREATE (f52)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f52)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f53)-[:IMPORTS {relation: 'resolved_imports'}]->(f4)
CREATE (f53)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f54)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f55)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f55)-[:IMPORTS {relation: 'resolved_imports'}]->(f7)
CREATE (f55)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f56)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f56)-[:IMPORTS {relation: 'resolved_imports'}]->(f8)
CREATE (f56)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f56)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f56)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f56)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f56)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f57)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f57)-[:IMPORTS {relation: 'resolved_imports'}]->(f10)
CREATE (f57)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f58)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f58)-[:IMPORTS {relation: 'resolved_imports'}]->(f11)
CREATE (f58)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f59)-[:IMPORTS {relation: 'resolved_imports'}]->(f3)
CREATE (f59)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f60)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f60)-[:IMPORTS {relation: 'resolved_imports'}]->(f12)
CREATE (f60)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f61)-[:IMPORTS {relation: 'resolved_imports'}]->(f14)
CREATE (f61)-[:IMPORTS {relation: 'resolved_imports'}]->(f3)
CREATE (f61)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f62)-[:IMPORTS {relation: 'resolved_imports'}]->(f15)
CREATE (f62)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f63)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f64)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f64)-[:IMPORTS {relation: 'resolved_imports'}]->(f28)
CREATE (f65)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f65)-[:IMPORTS {relation: 'resolved_imports'}]->(f28)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f43)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f31)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f36)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f45)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f38)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f37)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f32)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f47)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f42)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f33)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f35)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f41)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f44)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f48)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f39)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f46)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f40)
CREATE (f66)-[:IMPORTS {relation: 'resolved_imports'}]->(f34)
CREATE (f67)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f67)-[:IMPORTS {relation: 'resolved_imports'}]->(f19)
CREATE (f68)-[:IMPORTS {relation: 'resolved_imports'}]->(f5)
CREATE (f68)-[:IMPORTS {relation: 'resolved_imports'}]->(f9)
CREATE (f68)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f68)-[:IMPORTS {relation: 'resolved_imports'}]->(f18)
CREATE (f68)-[:IMPORTS {relation: 'resolved_imports'}]->(f20)
CREATE (f69)-[:IMPORTS {relation: 'resolved_imports'}]->(f21)
CREATE (f70)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f70)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f70)-[:IMPORTS {relation: 'resolved_imports'}]->(f22)
CREATE (f71)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f71)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f71)-[:IMPORTS {relation: 'resolved_imports'}]->(f23)
CREATE (f72)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f72)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f72)-[:IMPORTS {relation: 'resolved_imports'}]->(f24)
CREATE (f73)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f73)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f73)-[:IMPORTS {relation: 'resolved_imports'}]->(f25)
CREATE (f74)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f74)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f74)-[:IMPORTS {relation: 'resolved_imports'}]->(f26)
CREATE (f75)-[:IMPORTS {relation: 'resolved_imports'}]->(f6)
CREATE (f75)-[:IMPORTS {relation: 'resolved_imports'}]->(f16)
CREATE (f75)-[:IMPORTS {relation: 'resolved_imports'}]->(f26)
CREATE (f75)-[:IMPORTS {relation: 'resolved_imports'}]->(f24)
CREATE (f75)-[:IMPORTS {relation: 'resolved_imports'}]->(f21)
// Total: 76 nodes, 228 edges