import argparse
import logging
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

@dataclass(frozen=True)
class Config:
    """Centralized, immutable configuration. No magic numbers or hardcoded paths."""
    github_user: str = ""
    target_branch: str = "docs-export"
    commit_message: str = "docs: auto-generate knowledge base with readmenator"
    pr_title: str = "Documentation Export: Auto-generated Knowledge Base"
    pr_body_template: str = (
        "Automated documentation export generated on {timestamp}.\n\n"
        "This PR adds `KNOWLEDGE_BASE.md` to the root and `docs/KNOWLEDGE_BASE.md`.\n\n"
        "Each run replaces this branch (and closes any previous PR using the same head), "
        "so only the latest snapshot is open at any time.\n\n"
        "Generated by `readmenator_orchestrator.py`."
    )
    readmenator_script_name: str = "readmenator.py"
    output_filename: str = "KNOWLEDGE_BASE.md"
    docs_subdir: str = "docs"
    max_repos: int = 1000
    skip_repos: tuple = ("ReadMenator", "security_issue")
    git_user_name: str = "readmenator-bot"
    git_user_email: str = "readmenator-bot@users.noreply.github.com"
    subprocess_timeout: int = 300


class GitHubClient:
    """Handles all interactions with the GitHub API via the gh CLI."""

    def __init__(self, config: Config) -> None:
        """Initializes the client with configuration and resolves the GitHub user."""
        self.config = config
        self.user = self._resolve_user()

    def _resolve_user(self) -> str:
        """Resolves the authenticated GitHub username."""
        if self.config.github_user:
            return self.config.github_user
        
        github_repo = os.getenv("GITHUB_REPOSITORY")
        if github_repo:
            return github_repo.split("/")[0]

        try:
            result = subprocess.run(
                ["gh", "api", "user", "--jq", ".login"],
                capture_output=True, text=True, check=True
            )
            return result.stdout.strip()
        except subprocess.CalledProcessError:
            raise EnvironmentError("Could not resolve GitHub user. Set GITHUB_USER env var or ensure gh is authenticated.")

    def list_repos(self) -> list:
        """Retrieves a list of all repositories for the authenticated user."""
        result = subprocess.run(
            ["gh", "repo", "list", self.user, "--limit", str(self.config.max_repos), "--json", "name", "-q", ".[].name"],
            capture_output=True, text=True, check=True
        )
        return [r for r in result.stdout.strip().split('\n') if r]

    def close_existing_prs(self, repo: str) -> None:
        """Closes all existing pull requests for the target branch."""
        safe_branch = self.config.target_branch.replace('"', '\\"')
        jq_filter = f'.[] | select(.headRefName == "{safe_branch}") | .number'
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", f"{self.user}/{repo}", "--state", "all", "--json", "number,headRefName", "--jq", jq_filter],
            capture_output=True, text=True
        )
        for pr_num in result.stdout.strip().split('\n'):
            if pr_num:
                subprocess.run(
                    ["gh", "pr", "close", pr_num, "--repo", f"{self.user}/{repo}", "--delete-branch", "false"],
                    capture_output=True
                )

    def delete_remote_branch(self, repo: str) -> None:
        """Deletes the remote target branch if it exists."""
        subprocess.run(
            ["gh", "api", "-X", "DELETE", f"repos/{self.user}/{repo}/git/refs/heads/{self.config.target_branch}"],
            capture_output=True
        )

    def create_pr(self, repo: str, default_branch: str, timestamp: str) -> str:
        """Creates a new pull request for the generated documentation."""
        body = self.config.pr_body_template.format(timestamp=timestamp)
        result = subprocess.run(
            [
                "gh", "pr", "create",
                "--repo", f"{self.user}/{repo}",
                "--base", default_branch,
                "--head", self.config.target_branch,
                "--title", self.config.pr_title,
                "--body", body
            ],
            capture_output=True, text=True
        )
        return result.stdout.strip()


class RepositoryProcessor:
    """Processes individual repositories: clones, generates docs, commits, and pushes."""

    def __init__(self, config: Config, github_client: GitHubClient) -> None:
        """Initializes the processor with configuration and GitHub client."""
        self.config = config
        self.github = github_client
        self.token = os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN")

    def _configure_git_auth(self, repo_dir: Path) -> None:
        """Configures Git to use the GitHub token for authentication."""
        if not self.token:
            return
        
        repo_url = f"https://{self.token}@github.com/{self.github.user}"
        subprocess.run(
            ["git", "remote", "set-url", "origin", f"{repo_url}.git"],
            cwd=repo_dir, check=True, capture_output=True
        )

    def process(self, repo: str) -> tuple:
        """Executes the full processing pipeline for a single repository."""
        default_branch = self._get_default_branch(repo)
        if not default_branch:
            return False, "Failed to retrieve default branch"

        temp_dir = self._clone_repository(repo)
        if not temp_dir:
            return False, "Failed to clone repository"

        try:
            generated_file = self._run_readmenator(temp_dir)
            if not generated_file or not generated_file.exists():
                return False, "Readmenator did not generate the output file"

            self._copy_to_docs_dir(temp_dir, generated_file)
            
            if not self._commit_and_push(temp_dir, repo):
                return False, "No changes to commit or push failed"

            pr_url = self.github.create_pr(repo, default_branch, datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
            return True, pr_url
        finally:
            self._cleanup_temp_dir(temp_dir)

    def _get_default_branch(self, repo: str) -> Optional[str]:
        """Retrieves the default branch name for the repository."""
        try:
            result = subprocess.run(
                ["gh", "api", f"repos/{self.github.user}/{repo}", "--jq", ".default_branch"],
                capture_output=True, text=True, check=True
            )
            return result.stdout.strip()
        except subprocess.CalledProcessError:
            return None

    def _clone_repository(self, repo: str) -> Optional[Path]:
        """Clones the repository into a secure temporary directory."""
        temp_dir = Path(tempfile.mkdtemp(prefix=f"readmenator_{repo}_"))
        try:
            # Use token for cloning if available to avoid rate limits or auth issues
            clone_url = f"https://github.com/{self.github.user}/{repo}.git"
            if self.token:
                clone_url = f"https://{self.token}@github.com/{self.github.user}/{repo}.git"
            
            subprocess.run(
                ["git", "clone", "--depth", "1", clone_url, str(temp_dir)],
                check=True, capture_output=True, text=True
            )
            return temp_dir
        except subprocess.CalledProcessError as e:
            logging.error("Failed to clone %s: %s", repo, e.stderr)
            self._cleanup_temp_dir(temp_dir)
            return None

    def _run_readmenator(self, repo_dir: Path) -> Optional[Path]:
        """Executes the readmenator script on the cloned repository."""
        script_path = Path(__file__).parent / self.config.readmenator_script_name
        if not script_path.exists():
            logging.error("Readmenator script not found at %s", script_path)
            return None

        output_file = repo_dir / self.config.output_filename
        try:
            subprocess.run(
                [sys.executable, str(script_path), str(repo_dir)],
                check=True,
                capture_output=True,
                text=True,
                timeout=self.config.subprocess_timeout
            )
            return output_file
        except subprocess.CalledProcessError as e:
            logging.error("Readmenator execution failed: %s", e.stderr)
            return None
        except subprocess.TimeoutExpired:
            logging.error("Readmenator execution timed out")
            return None

    def _copy_to_docs_dir(self, repo_dir: Path, generated_file: Path) -> None:
        """Copies the generated knowledge base to the docs subdirectory."""
        docs_dir = repo_dir / self.config.docs_subdir
        docs_dir.mkdir(exist_ok=True)
        target_file = docs_dir / self.config.output_filename
        shutil.copy2(generated_file, target_file)

    def _commit_and_push(self, repo_dir: Path, repo: str) -> bool:
        """Commits and pushes the generated documentation to the target branch."""
        env = os.environ.copy()
        env["GIT_AUTHOR_NAME"] = self.config.git_user_name
        env["GIT_AUTHOR_EMAIL"] = self.config.git_user_email
        env["GIT_COMMITTER_NAME"] = self.config.git_user_name
        env["GIT_COMMITTER_EMAIL"] = self.config.git_user_email

        try:
            self._configure_git_auth(repo_dir)
            
            subprocess.run(
                ["git", "checkout", "-B", self.config.target_branch], 
                cwd=repo_dir, check=True, capture_output=True, env=env
            )
            subprocess.run(
                ["git", "add", self.config.output_filename, f"{self.config.docs_subdir}/{self.config.output_filename}"], 
                cwd=repo_dir, check=True, capture_output=True, env=env
            )
            
            diff_result = subprocess.run(
                ["git", "diff", "--cached", "--quiet"], 
                cwd=repo_dir, capture_output=True, env=env
            )
            if diff_result.returncode == 0:
                logging.info("No changes to commit for %s", repo)
                return False

            subprocess.run(
                ["git", "commit", "-m", self.config.commit_message], 
                cwd=repo_dir, check=True, capture_output=True, env=env
            )
            subprocess.run(
                ["git", "push", "-u", "origin", self.config.target_branch], 
                cwd=repo_dir, check=True, capture_output=True, env=env
            )
            return True
        except subprocess.CalledProcessError as e:
            logging.error("Git operation failed: %s", e.stderr)
            return False

    def _cleanup_temp_dir(self, temp_dir: Path) -> None:
        """Safely removes the temporary directory."""
        if temp_dir and temp_dir.exists():
            shutil.rmtree(temp_dir, ignore_errors=True)


class Orchestrator:
    """Main orchestrator that coordinates the documentation generation across all repositories."""

    def __init__(self, config: Optional[Config] = None) -> None:
        """Initializes the orchestrator with configuration."""
        self.config = config or Config()
        self.github = GitHubClient(self.config)
        self.processor = RepositoryProcessor(self.config, self.github)

    def run(self, dry_run: bool = False, only_repo: Optional[str] = None) -> None:
        """Executes the orchestration pipeline."""
        logging.info("Fetching repositories for user: %s", self.github.user)
        repos = self.github.list_repos()
        
        if not repos:
            logging.error("No repositories found.")
            return

        logging.info("Total repositories found: %d", len(repos))
        
        success_count = 0
        skip_count = 0
        fail_count = 0

        for repo in repos:
            if repo in self.config.skip_repos:
                logging.info("Skipping %s (in skip list)", repo)
                skip_count += 1
                continue

            if only_repo and repo != only_repo:
                continue

            logging.info("Processing repository: %s", repo)

            if dry_run:
                logging.info("[DRY-RUN] Would process %s", repo)
                continue

            self.github.close_existing_prs(repo)
            self.github.delete_remote_branch(repo)

            success, message = self.processor.process(repo)
            if success:
                logging.info("Successfully processed %s: %s", repo, message)
                success_count += 1
            else:
                logging.warning("Failed to process %s: %s", repo, message)
                if "No changes" in message:
                    skip_count += 1
                else:
                    fail_count += 1

        logging.info("Orchestration complete. Success: %d, Skipped: %d, Failed: %d", success_count, skip_count, fail_count)


class TestOrchestrator(unittest.TestCase):
    """Test suite for the ReadMenator Orchestrator (SDD + TDD + BDD)."""

    def setUp(self) -> None:
        """Sets up test fixtures."""
        self.config = Config(github_user="test_user", target_branch="test-branch")
        self.temp_dir = Path(tempfile.mkdtemp())

    def tearDown(self) -> None:
        """Tears down test fixtures."""
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def test_config_immutability(self) -> None:
        """Validates that the Config dataclass is immutable."""
        with self.assertRaises(AttributeError):
            self.config.target_branch = "new-branch"

    def test_config_defaults(self) -> None:
        """Validates default configuration values."""
        default_config = Config()
        self.assertEqual(default_config.output_filename, "KNOWLEDGE_BASE.md")
        self.assertEqual(default_config.docs_subdir, "docs")
        self.assertEqual(default_config.subprocess_timeout, 300)

    def test_skip_repos_logic(self) -> None:
        """Validates that critical repositories are skipped by default."""
        self.assertIn("ReadMenator", self.config.skip_repos)
        self.assertIn("security_issue", self.config.skip_repos)

    def test_jq_filter_escaping(self) -> None:
        """Validates that jq filters are safely escaped against injection."""
        config = Config(target_branch='test"branch')
        client = GitHubClient(config)
        self.assertIsNotNone(client.config.target_branch)


def parse_arguments() -> argparse.Namespace:
    """Parses command line arguments."""
    parser = argparse.ArgumentParser(description="ReadMenator Orchestrator")
    parser.add_argument("--dry-run", action="store_true", help="Simulate the process without making changes")
    parser.add_argument("--only", type=str, help="Process only the specified repository")
    parser.add_argument("--test", action="store_true", help="Run the built-in test suite")
    return parser.parse_args()


def main() -> None:
    """Main entry point for the orchestrator."""
    args = parse_arguments()
    
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s"
    )

    if args.test:
        sys.argv = [sys.argv[0]]
        unittest.main(verbosity=2)
        return

    config = Config()
    orchestrator = Orchestrator(config)
    orchestrator.run(dry_run=args.dry_run, only_repo=args.only)


if __name__ == "__main__":
    main()
