"""Contract tests for AI agent file injection.

SDD + TDD + BDD: Each test validates a specific behavioral contract
of the AgentInjector for injecting/deleting knowledge base references
into AI agent instruction files.
"""

from __future__ import annotations

import shutil
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from readmenator._agent_injector import AgentInjector


class TestAgentInjectorInjectBehavior(unittest.TestCase):
    """BDD: AgentInjector injection contract."""

    def setUp(self) -> None:
        self.tmpdir = tempfile.mkdtemp()
        self.root = Path(self.tmpdir)
        self.injector = AgentInjector(kb_filename="KNOWLEDGE_BASE.md")

    def tearDown(self) -> None:
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_inject_into_agents_md_adds_kb_link(self):
        path = self.root / "AGENTS.md"
        path.write_text("# Agent Instructions\n\nBe helpful.\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 1)
        content = path.read_text()
        self.assertIn("KNOWLEDGE_BASE.md", content)
        self.assertIn("<!-- readmenator-agent-kb-link -->", content)

    def test_inject_into_claude_md_adds_kb_link(self):
        path = self.root / "CLAUDE.md"
        path.write_text("# Claude Rules\n\nDo things.\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 1)
        content = path.read_text()
        self.assertIn("KNOWLEDGE_BASE.md", content)

    def test_inject_into_cursorrules_adds_kb_link(self):
        path = self.root / ".cursorrules"
        path.write_text("rule1\nrule2\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 1)
        content = path.read_text()
        self.assertIn("KNOWLEDGE_BASE.md", content)

    def test_inject_into_github_copilot_instructions(self):
        gh_dir = self.root / ".github"
        gh_dir.mkdir()
        path = gh_dir / "copilot-instructions.md"
        path.write_text("# Copilot instructions\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 1)
        content = path.read_text()
        self.assertIn("KNOWLEDGE_BASE.md", content)

    def test_inject_replaces_old_injection_without_regen_command(self):
        path = self.root / "CLAUDE.md"
        old_injection = (
            "<!-- readmenator-agent-kb-link -->\n"
            "## Project Knowledge Base\n\n"
            "This project contains a KNOWLEDGE_BASE.md file generated by ReadMenator.\n"
            "<!-- /readmenator-agent-kb-link -->"
        )
        path.write_text("# Rules\n\n" + old_injection + "\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 1)
        content = path.read_text()
        self.assertIn("pip install readmenator && readmenator .", content)
        self.assertNotIn("file generated by", content)

    def test_inject_skips_when_already_up_to_date(self):
        path = self.root / "CLAUDE.md"
        new_injection = (
            "<!-- readmenator-agent-kb-link -->\n"
            "## Project Knowledge Base\n\n"
            "If KNOWLEDGE_BASE.md does not exist or is outdated, regenerate it by running:\n\n"
            "    pip install readmenator && readmenator .\n"
            "<!-- /readmenator-agent-kb-link -->"
        )
        path.write_text("# Rules\n\n" + new_injection + "\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 0)

    def test_inject_into_cursor_rules_mdc_glob(self):
        cursor_dir = self.root / ".cursor" / "rules"
        cursor_dir.mkdir(parents=True)
        path = cursor_dir / "my-rule.mdc"
        path.write_text("---\ndescription: test\n---\nRule content\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 1)
        content = path.read_text()
        self.assertIn("KNOWLEDGE_BASE.md", content)

    def test_inject_is_idempotent_does_not_duplicate(self):
        path = self.root / "AGENTS.md"
        path.write_text("# Agent Instructions\n")
        first = self.injector.inject(str(self.root))
        self.assertEqual(first, 1)
        second = self.injector.inject(str(self.root))
        self.assertEqual(second, 0)
        content = path.read_text()
        occurrences = content.count("<!-- readmenator-agent-kb-link -->")
        self.assertEqual(occurrences, 1)

    def test_inject_no_agent_files_returns_zero(self):
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 0)

    def test_inject_preserves_existing_content(self):
        original = "# My Agent Config\n\nSome rules.\n"
        path = self.root / "CLAUDE.md"
        path.write_text(original)
        self.injector.inject(str(self.root))
        content = path.read_text()
        self.assertTrue(content.startswith(original.strip()))

    def test_inject_multiple_agent_files(self):
        (self.root / "AGENTS.md").write_text("# Agents\n")
        (self.root / "CLAUDE.md").write_text("# Claude\n")
        (self.root / "SOUL.md").write_text("# Soul\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 3)

    def test_inject_plain_text_format_for_yaml(self):
        path = self.root / ".aider.conf.yml"
        path.write_text("model: gpt-4\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 1)
        content = path.read_text()
        self.assertIn("KNOWLEDGE_BASE.md", content)
        self.assertNotIn("##", content.split("Project Knowledge Base")[1].split("<!--")[0])

    def test_custom_kb_filename_works(self):
        injector = AgentInjector(kb_filename="docs/KB.md")
        path = self.root / "AGENTS.md"
        path.write_text("# Agents\n")
        injector.inject(str(self.root))
        content = path.read_text()
        self.assertIn("docs/KB.md", content)

    def test_injection_includes_regeneration_command(self):
        path = self.root / "AGENTS.md"
        path.write_text("# Agents\n")
        self.injector.inject(str(self.root))
        content = path.read_text()
        self.assertIn("pip install readmenator && readmenator .", content)

    def test_inject_does_not_execute_commands(self):
        path = self.root / "AGENTS.md"
        path.write_text("# Agents\n")
        with patch("subprocess.check_call") as mock_call:
            self.injector.inject(str(self.root))
            mock_call.assert_not_called()


class TestAgentInjectorRemoveBehavior(unittest.TestCase):
    """BDD: AgentInjector removal contract."""

    def setUp(self) -> None:
        self.tmpdir = tempfile.mkdtemp()
        self.root = Path(self.tmpdir)
        self.injector = AgentInjector(kb_filename="KNOWLEDGE_BASE.md")

    def tearDown(self) -> None:
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_remove_strips_injected_section(self):
        path = self.root / "AGENTS.md"
        original = "# Agent Instructions\n\nBe helpful.\n"
        path.write_text(original)
        self.injector._inject_single(path)
        removed = self.injector.remove(str(self.root))
        self.assertEqual(removed, 1)
        content = path.read_text()
        self.assertNotIn("<!-- readmenator-agent-kb-link -->", content)
        self.assertIn("Be helpful", content)

    def test_remove_without_injection_returns_zero(self):
        path = self.root / "AGENTS.md"
        path.write_text("# Agent Instructions\n")
        result = self.injector.remove(str(self.root))
        self.assertEqual(result, 0)

    def test_remove_no_files_returns_zero(self):
        result = self.injector.remove(str(self.root))
        self.assertEqual(result, 0)

    def test_remove_preserves_original_content(self):
        path = self.root / "CLAUDE.md"
        original = "# Rules\n\n1. Be helpful.\n2. Be concise.\n"
        path.write_text(original)
        self.injector._inject_single(path)
        self.injector.remove(str(self.root))
        content = path.read_text()
        self.assertIn("1. Be helpful.", content)
        self.assertIn("2. Be concise.", content)


class TestAgentInjectorFindFiles(unittest.TestCase):
    """BDD: AgentInjector file detection contract."""

    def setUp(self) -> None:
        self.tmpdir = tempfile.mkdtemp()
        self.root = Path(self.tmpdir)

    def tearDown(self) -> None:
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_finds_agents_md(self):
        (self.root / "AGENTS.md").write_text("")
        files = AgentInjector().find_agent_files(str(self.root))
        names = [f.name for f in files]
        self.assertIn("AGENTS.md", names)

    def test_finds_all_listed_files(self):
        for name in ("AGENTS.md", "CLAUDE.md", "SOUL.md", ".cursorrules"):
            (self.root / name).write_text("")
        files = AgentInjector().find_agent_files(str(self.root))
        names = {f.name for f in files}
        self.assertTrue({"AGENTS.md", "CLAUDE.md", "SOUL.md", ".cursorrules"}.issubset(names))

    def test_finds_cursor_rules_glob(self):
        cursor_dir = self.root / ".cursor" / "rules"
        cursor_dir.mkdir(parents=True)
        (cursor_dir / "rule1.mdc").write_text("")
        (cursor_dir / "rule2.mdc").write_text("")
        files = AgentInjector().find_agent_files(str(self.root))
        mdc_files = [f for f in files if f.suffix == ".mdc"]
        self.assertEqual(len(mdc_files), 2)

    def test_returns_empty_when_no_files(self):
        files = AgentInjector().find_agent_files(str(self.root))
        self.assertEqual(files, [])


class TestAgentInjectorEdgeCases(unittest.TestCase):
    """BDD: AgentInjector edge case contract."""

    def setUp(self) -> None:
        self.tmpdir = tempfile.mkdtemp()
        self.root = Path(self.tmpdir)
        self.injector = AgentInjector(kb_filename="KNOWLEDGE_BASE.md")

    def tearDown(self) -> None:
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_inject_into_empty_file(self):
        path = self.root / "AGENTS.md"
        path.write_text("")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 1)
        content = path.read_text()
        self.assertIn("KNOWLEDGE_BASE.md", content)

    def test_inject_respects_custom_agent_files_list(self):
        injector = AgentInjector(agent_files=("CUSTOM.md",))
        path = self.root / "CUSTOM.md"
        path.write_text("# Custom\n")
        count = injector.inject(str(self.root))
        self.assertEqual(count, 1)
        self.assertIn("KNOWLEDGE_BASE.md", path.read_text())

    def test_inject_does_not_touch_unlisted_files(self):
        path = self.root / "random_notes.md"
        path.write_text("# Notes\n")
        count = self.injector.inject(str(self.root))
        self.assertEqual(count, 0)
        self.assertNotIn("readmenator-agent-kb-link", path.read_text())


if __name__ == "__main__":
    unittest.main()
